# Travis CI Configuration File
# http://about.travis-ci.org/docs/user/languages/php/

language: php

php:
    - 5.3
    - 5.4
    - 5.5

env:
    - WP_VERSION=master WP_MULTISITE=0
    - WP_VERSION=4.0.0 WP_MULTISITE=0
    - WP_VERSION=3.9.1 WP_MULTISITE=0
    - WP_VERSION=3.8.1 WP_MULTISITE=0

before_script:
    - composer install --no-interaction --optimize-autoloader

branches:
  only:
    - working
